-- ============================================================
-- 경기북부 학사관리 시스템 - Supabase 초기 설정 SQL (v2026)
-- Supabase 대시보드 → SQL Editor 에서 전체 실행하세요.
-- 기존 데이터는 유지하고 누락된 테이블/컬럼만 안전하게 보강합니다.
-- ============================================================

-- ------------------------------------------------------------
-- 0) 공통: UUID 확장
-- ------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ------------------------------------------------------------
-- 1) 핵심 테이블 생성
-- ------------------------------------------------------------

-- 계정
CREATE TABLE IF NOT EXISTS accounts (
  id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  TEXT NOT NULL,
  role  TEXT NOT NULL DEFAULT 'staff',
  pw    TEXT NOT NULL
);

-- 과정
CREATE TABLE IF NOT EXISTS courses (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cat              TEXT,
  cc               TEXT,
  name             TEXT NOT NULL,
  code             TEXT,
  date_from        TEXT,
  date_to          TEXT,
  period           TEXT DEFAULT '',
  method           TEXT DEFAULT '대면',
  hours            NUMERIC DEFAULT 0,
  tgt              INTEGER DEFAULT 20,
  c_goal           INTEGER DEFAULT 18,
  e_goal           INTEGER DEFAULT 12,
  sched_days       TEXT DEFAULT '',
  sched_time_from  TEXT,
  sched_time_to    TEXT,
  break_minutes    INTEGER DEFAULT 60,
  notes            TEXT DEFAULT '',
  pdf_name         TEXT DEFAULT '',
  pdf_data         TEXT DEFAULT '',
  links            JSONB DEFAULT '[]'::jsonb
);

-- 훈련생
CREATE TABLE IF NOT EXISTS students (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cid                BIGINT,
  name               TEXT NOT NULL,
  gender             TEXT DEFAULT '',
  birth              TEXT,
  id_back            TEXT DEFAULT '',
  phone              TEXT DEFAULT '',
  phone2             TEXT DEFAULT '',
  addr_city          TEXT DEFAULT '',
  addr_detail        TEXT DEFAULT '',
  edu                TEXT DEFAULT '',
  major              TEXT DEFAULT '',
  career             TEXT DEFAULT '',
  cert               TEXT DEFAULT '',
  status             TEXT DEFAULT '미취업',
  unemp              BOOLEAN DEFAULT FALSE,
  disabled           BOOLEAN DEFAULT FALSE,
  veteran            BOOLEAN DEFAULT FALSE,
  itv_date           TEXT,
  itv_score          NUMERIC,
  itv_grade          TEXT DEFAULT '',
  itv_pass           BOOLEAN DEFAULT FALSE,
  memo               TEXT DEFAULT '',
  rate               NUMERIC DEFAULT 0,
  enrollment_status  TEXT DEFAULT '재학중',
  accumulated_hours  NUMERIC DEFAULT 0,
  status_change_date TEXT,
  dropout_reason     TEXT,
  employer_name      TEXT
);

-- 강사
CREATE TABLE IF NOT EXISTS instructors (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL,
  type         TEXT DEFAULT '주강사',
  category     TEXT DEFAULT '경기도 강사',
  subject      TEXT DEFAULT '',
  phone        TEXT DEFAULT '',
  email        TEXT DEFAULT '',
  career       TEXT DEFAULT '',
  cert         TEXT DEFAULT '',
  cids         JSONB DEFAULT '[]'::jsonb,
  note         TEXT DEFAULT '',
  hourly_rate  INTEGER DEFAULT 0,
  custom_dates JSONB DEFAULT '{}'::jsonb
);

-- 강의실
CREATE TABLE IF NOT EXISTS rooms (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  floor    INTEGER DEFAULT 0,
  name     TEXT NOT NULL,
  addr     TEXT DEFAULT '',
  capacity INTEGER DEFAULT 20,
  equip    TEXT DEFAULT ''
);

-- 강의실 예약
CREATE TABLE IF NOT EXISTS room_bookings (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id    BIGINT,
  course_id  BIGINT,
  label      TEXT DEFAULT '',
  start_date TEXT,
  end_date   TEXT,
  color      TEXT DEFAULT '#EA580C'
);

-- 출결
CREATE TABLE IF NOT EXISTS attendance (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id    BIGINT,
  student_id   BIGINT NOT NULL,
  date         TEXT NOT NULL,
  status       TEXT DEFAULT 'U',
  check_in     TEXT,
  check_out    TEXT,
  method       TEXT DEFAULT 'manual',
  reason       TEXT,
  absence_type TEXT
);

-- 일정 예외
CREATE TABLE IF NOT EXISTS course_schedule_overrides (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT NOT NULL,
  date      TEXT NOT NULL,
  type      TEXT NOT NULL,
  time_from TEXT,
  time_to   TEXT,
  hours     NUMERIC DEFAULT 0,
  reason    TEXT DEFAULT ''
);

-- 상태 변경 이력
CREATE TABLE IF NOT EXISTS status_changes (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id      BIGINT,
  course_id       BIGINT,
  previous_status TEXT,
  new_status      TEXT,
  change_date     TEXT,
  reason          TEXT,
  employer_name   TEXT,
  changed_by      TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- 공휴일
CREATE TABLE IF NOT EXISTS holidays (
  date TEXT PRIMARY KEY
);

-- 증명서 발급 이력
CREATE TABLE IF NOT EXISTS cert_issuances (
  id           TEXT PRIMARY KEY,
  student_id   BIGINT,
  student_name TEXT,
  course_id    BIGINT,
  course_name  TEXT,
  doc_type     TEXT,
  cert_no      TEXT,
  full_no      TEXT,
  issue_date   TEXT,
  issued_at    TIMESTAMPTZ DEFAULT NOW(),
  issue_reason TEXT DEFAULT '최초발급',
  issue_channel TEXT DEFAULT '미리보기',
  issue_status TEXT DEFAULT '정상',
  completion_status TEXT,
  attendance_rate NUMERIC DEFAULT 0,
  issued_by TEXT,
  original_issue_id TEXT,
  cancelled_at TIMESTAMPTZ,
  cancel_reason TEXT,
  cancelled_by TEXT,
  admin_memo TEXT DEFAULT '',
  print_count INTEGER DEFAULT 0,
  pdf_count INTEGER DEFAULT 0,
  image_count INTEGER DEFAULT 0,
  last_output_at TIMESTAMPTZ
);

-- ------------------------------------------------------------
-- 2) 누락 컬럼 보강 (기존 DB 마이그레이션)
-- ------------------------------------------------------------

ALTER TABLE courses ADD COLUMN IF NOT EXISTS cat TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS cc TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS code TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS date_from TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS date_to TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS period TEXT DEFAULT '';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS method TEXT DEFAULT '대면';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS hours NUMERIC DEFAULT 0;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS tgt INTEGER DEFAULT 20;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS c_goal INTEGER DEFAULT 18;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS e_goal INTEGER DEFAULT 12;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS sched_days TEXT DEFAULT '';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS sched_time_from TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS sched_time_to TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS break_minutes INTEGER DEFAULT 60;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT '';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS pdf_name TEXT DEFAULT '';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS pdf_data TEXT DEFAULT '';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS links JSONB DEFAULT '[]'::jsonb;

ALTER TABLE students ADD COLUMN IF NOT EXISTS cid BIGINT;
ALTER TABLE students ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE students ADD COLUMN IF NOT EXISTS gender TEXT DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS birth TEXT;
ALTER TABLE students ADD COLUMN IF NOT EXISTS id_back TEXT DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS phone TEXT DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS phone2 TEXT DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS addr_city TEXT DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS addr_detail TEXT DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS edu TEXT DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS major TEXT DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS career TEXT DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS cert TEXT DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS status TEXT DEFAULT '미취업';
ALTER TABLE students ADD COLUMN IF NOT EXISTS unemp BOOLEAN DEFAULT FALSE;
ALTER TABLE students ADD COLUMN IF NOT EXISTS disabled BOOLEAN DEFAULT FALSE;
ALTER TABLE students ADD COLUMN IF NOT EXISTS veteran BOOLEAN DEFAULT FALSE;
ALTER TABLE students ADD COLUMN IF NOT EXISTS itv_date TEXT;
ALTER TABLE students ADD COLUMN IF NOT EXISTS itv_score NUMERIC;
ALTER TABLE students ADD COLUMN IF NOT EXISTS itv_grade TEXT DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS itv_pass BOOLEAN DEFAULT FALSE;
ALTER TABLE students ADD COLUMN IF NOT EXISTS memo TEXT DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS rate NUMERIC DEFAULT 0;
ALTER TABLE students ADD COLUMN IF NOT EXISTS enrollment_status TEXT DEFAULT '재학중';
ALTER TABLE students ADD COLUMN IF NOT EXISTS accumulated_hours NUMERIC DEFAULT 0;
ALTER TABLE students ADD COLUMN IF NOT EXISTS status_change_date TEXT;
ALTER TABLE students ADD COLUMN IF NOT EXISTS dropout_reason TEXT;
ALTER TABLE students ADD COLUMN IF NOT EXISTS employer_name TEXT;

ALTER TABLE instructors ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE instructors ADD COLUMN IF NOT EXISTS type TEXT DEFAULT '주강사';
ALTER TABLE instructors ADD COLUMN IF NOT EXISTS category TEXT DEFAULT '경기도 강사';
ALTER TABLE instructors ADD COLUMN IF NOT EXISTS subject TEXT DEFAULT '';
ALTER TABLE instructors ADD COLUMN IF NOT EXISTS phone TEXT DEFAULT '';
ALTER TABLE instructors ADD COLUMN IF NOT EXISTS email TEXT DEFAULT '';
ALTER TABLE instructors ADD COLUMN IF NOT EXISTS career TEXT DEFAULT '';
ALTER TABLE instructors ADD COLUMN IF NOT EXISTS cert TEXT DEFAULT '';
ALTER TABLE instructors ADD COLUMN IF NOT EXISTS cids JSONB DEFAULT '[]'::jsonb;
ALTER TABLE instructors ADD COLUMN IF NOT EXISTS note TEXT DEFAULT '';
ALTER TABLE instructors ADD COLUMN IF NOT EXISTS hourly_rate INTEGER DEFAULT 0;
ALTER TABLE instructors ADD COLUMN IF NOT EXISTS custom_dates JSONB DEFAULT '{}'::jsonb;

ALTER TABLE rooms ADD COLUMN IF NOT EXISTS floor INTEGER DEFAULT 0;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS addr TEXT DEFAULT '';
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS capacity INTEGER DEFAULT 20;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS equip TEXT DEFAULT '';

ALTER TABLE room_bookings ADD COLUMN IF NOT EXISTS room_id BIGINT;
ALTER TABLE room_bookings ADD COLUMN IF NOT EXISTS course_id BIGINT;
ALTER TABLE room_bookings ADD COLUMN IF NOT EXISTS label TEXT DEFAULT '';
ALTER TABLE room_bookings ADD COLUMN IF NOT EXISTS start_date TEXT;
ALTER TABLE room_bookings ADD COLUMN IF NOT EXISTS end_date TEXT;
ALTER TABLE room_bookings ADD COLUMN IF NOT EXISTS color TEXT DEFAULT '#EA580C';

ALTER TABLE attendance ADD COLUMN IF NOT EXISTS course_id BIGINT;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS student_id BIGINT;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS date TEXT;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'U';
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS check_in TEXT;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS check_out TEXT;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS method TEXT DEFAULT 'manual';
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS reason TEXT;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS absence_type TEXT;

ALTER TABLE course_schedule_overrides ADD COLUMN IF NOT EXISTS course_id BIGINT;
ALTER TABLE course_schedule_overrides ADD COLUMN IF NOT EXISTS date TEXT;
ALTER TABLE course_schedule_overrides ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE course_schedule_overrides ADD COLUMN IF NOT EXISTS time_from TEXT;
ALTER TABLE course_schedule_overrides ADD COLUMN IF NOT EXISTS time_to TEXT;
ALTER TABLE course_schedule_overrides ADD COLUMN IF NOT EXISTS hours NUMERIC DEFAULT 0;
ALTER TABLE course_schedule_overrides ADD COLUMN IF NOT EXISTS reason TEXT DEFAULT '';

ALTER TABLE status_changes ADD COLUMN IF NOT EXISTS student_id BIGINT;
ALTER TABLE status_changes ADD COLUMN IF NOT EXISTS course_id BIGINT;
ALTER TABLE status_changes ADD COLUMN IF NOT EXISTS previous_status TEXT;
ALTER TABLE status_changes ADD COLUMN IF NOT EXISTS new_status TEXT;
ALTER TABLE status_changes ADD COLUMN IF NOT EXISTS change_date TEXT;
ALTER TABLE status_changes ADD COLUMN IF NOT EXISTS reason TEXT;
ALTER TABLE status_changes ADD COLUMN IF NOT EXISTS employer_name TEXT;
ALTER TABLE status_changes ADD COLUMN IF NOT EXISTS changed_by TEXT;
ALTER TABLE status_changes ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS student_id BIGINT;
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS student_name TEXT;
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS course_id BIGINT;
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS course_name TEXT;
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS doc_type TEXT;
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS cert_no TEXT;
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS full_no TEXT;
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS issue_date TEXT;
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS issued_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS issue_reason TEXT DEFAULT '최초발급';
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS issue_channel TEXT DEFAULT '미리보기';
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS issue_status TEXT DEFAULT '정상';
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS completion_status TEXT;
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS attendance_rate NUMERIC DEFAULT 0;
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS issued_by TEXT;
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS original_issue_id TEXT;
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ;
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS cancel_reason TEXT;
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS cancelled_by TEXT;
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS admin_memo TEXT DEFAULT '';
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS print_count INTEGER DEFAULT 0;
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS pdf_count INTEGER DEFAULT 0;
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS image_count INTEGER DEFAULT 0;
ALTER TABLE cert_issuances ADD COLUMN IF NOT EXISTS last_output_at TIMESTAMPTZ;

-- ------------------------------------------------------------
-- 3) 제약/인덱스
-- ------------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS attendance_student_date_course_uidx
  ON attendance (student_id, date, course_id);

CREATE UNIQUE INDEX IF NOT EXISTS course_schedule_overrides_course_date_uidx
  ON course_schedule_overrides (course_id, date);

CREATE INDEX IF NOT EXISTS students_cid_idx ON students (cid);
CREATE INDEX IF NOT EXISTS room_bookings_room_id_idx ON room_bookings (room_id);
CREATE INDEX IF NOT EXISTS room_bookings_course_id_idx ON room_bookings (course_id);
CREATE INDEX IF NOT EXISTS status_changes_student_course_idx ON status_changes (student_id, course_id);

-- ------------------------------------------------------------
-- 4) 기본 계정 시드
-- ------------------------------------------------------------

INSERT INTO accounts (id, name, role, pw)
VALUES
  (1, '관리자', 'admin', 'admin1234'),
  (2, '김담당', 'staff', 'gjf2026'),
  (3, '이담당', 'staff', 'gjf2026')
ON CONFLICT (id) DO NOTHING;

DO $$
DECLARE
  seq_name TEXT;
BEGIN
  SELECT pg_get_serial_sequence('accounts', 'id') INTO seq_name;
  IF seq_name IS NOT NULL THEN
    EXECUTE format(
      'SELECT setval(%L, GREATEST((SELECT COALESCE(MAX(id), 0) FROM accounts), 1), true)',
      seq_name
    );
  END IF;
END $$;

-- ------------------------------------------------------------
-- 5) RLS 비활성화 (내부 관리자 시스템 용도)
-- ------------------------------------------------------------

ALTER TABLE accounts                  DISABLE ROW LEVEL SECURITY;
ALTER TABLE courses                   DISABLE ROW LEVEL SECURITY;
ALTER TABLE students                  DISABLE ROW LEVEL SECURITY;
ALTER TABLE instructors               DISABLE ROW LEVEL SECURITY;
ALTER TABLE rooms                     DISABLE ROW LEVEL SECURITY;
ALTER TABLE room_bookings             DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendance                DISABLE ROW LEVEL SECURITY;
ALTER TABLE holidays                  DISABLE ROW LEVEL SECURITY;
ALTER TABLE course_schedule_overrides DISABLE ROW LEVEL SECURITY;
ALTER TABLE status_changes            DISABLE ROW LEVEL SECURITY;
ALTER TABLE cert_issuances            DISABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- 6) 출석/수료 시간 계산 로직 업데이트 (manual adjustment + break inclusion)
-- ------------------------------------------------------------

-- courses 테이블: 쉬는시간 포함 여부 컬럼 추가
ALTER TABLE courses
ADD COLUMN IF NOT EXISTS include_break_in_hours BOOLEAN DEFAULT TRUE;

UPDATE courses
SET include_break_in_hours = TRUE
WHERE include_break_in_hours IS NULL;

-- attendance 테이블: 수동 보정 컬럼 추가
ALTER TABLE attendance
ADD COLUMN IF NOT EXISTS manual_add_hours    NUMERIC  DEFAULT 0,
ADD COLUMN IF NOT EXISTS manual_deduct_hours NUMERIC  DEFAULT 0,
ADD COLUMN IF NOT EXISTS manual_reason       TEXT,
ADD COLUMN IF NOT EXISTS manual_memo         TEXT,
ADD COLUMN IF NOT EXISTS manual_updated_by   TEXT,
ADD COLUMN IF NOT EXISTS manual_updated_at   TIMESTAMPTZ;

UPDATE attendance
SET
  manual_add_hours    = COALESCE(manual_add_hours,    0),
  manual_deduct_hours = COALESCE(manual_deduct_hours, 0);
