-- ============================================================
-- 경기북부 직업교육 학사관리시스템 — Supabase 초기 세팅 스크립트
-- Supabase SQL Editor에서 전체 복사 → Run (Ctrl+Enter)
-- ============================================================

-- ==========================================
-- 1. 데이터베이스 테이블 생성
-- ==========================================

-- 과정 테이블
CREATE TABLE IF NOT EXISTS courses (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cat         TEXT,
  cc          TEXT,
  name        TEXT NOT NULL,
  code        TEXT,
  date_from   TEXT,
  date_to     TEXT,
  period      TEXT,
  method      TEXT,
  hours       NUMERIC,
  tgt         INTEGER DEFAULT 0,
  c_goal      INTEGER DEFAULT 0,
  e_goal      INTEGER DEFAULT 0,
  sched_days  TEXT,
  sched_time_from TEXT,
  sched_time_to   TEXT,
  notes       TEXT,
  pdf_name    TEXT,
  pdf_data    TEXT,
  links       JSONB DEFAULT '[]'::JSONB,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 훈련생 테이블 (id는 IDENTITY — 앱이 직접 생성하지 않음)
CREATE TABLE IF NOT EXISTS students (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cid         BIGINT REFERENCES courses(id) ON DELETE SET NULL,
  name        TEXT NOT NULL,
  gender      TEXT DEFAULT '',
  birth       TEXT,
  id_back     TEXT DEFAULT '',
  phone       TEXT DEFAULT '',
  phone2      TEXT DEFAULT '',
  addr_city   TEXT DEFAULT '',
  addr_detail TEXT DEFAULT '',
  edu         TEXT DEFAULT '',
  major       TEXT DEFAULT '',
  career      TEXT DEFAULT '',
  cert        TEXT DEFAULT '',
  status      TEXT DEFAULT '미취업',
  unemp       BOOLEAN DEFAULT FALSE,
  disabled    BOOLEAN DEFAULT FALSE,
  veteran     BOOLEAN DEFAULT FALSE,
  itv_date    TEXT,
  itv_score   NUMERIC,
  itv_grade   TEXT DEFAULT '',
  itv_pass    BOOLEAN DEFAULT FALSE,
  memo        TEXT DEFAULT '',
  rate        NUMERIC DEFAULT 0,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 출결 테이블 (신규 설치용)
-- status: O=출석, L=지각, A=결석, U=미확인
-- method: manual(수동입력) | qr(QR스캔)
CREATE TABLE IF NOT EXISTS attendance (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id   BIGINT REFERENCES courses(id) ON DELETE SET NULL,
  student_id  BIGINT REFERENCES students(id) ON DELETE CASCADE,
  date        TEXT NOT NULL,
  status      TEXT DEFAULT 'U',
  check_in    TEXT,
  check_out   TEXT,
  method      TEXT DEFAULT 'manual',
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 기존 DB 마이그레이션: 새 스키마로 전환
-- ==========================================

-- 1) 기존 설치 환경: course_id 컬럼 추가 (이미 있으면 무시)
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS course_id BIGINT REFERENCES courses(id) ON DELETE SET NULL;

-- 2) 새 컬럼 추가
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS check_in  TEXT;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS check_out TEXT;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS method    TEXT DEFAULT 'manual';
-- status 컬럼이 없으면 추가 (기존 DB는 있음)
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'U';

-- 컬럼 추가 직후 스키마 캐시 갱신 (check_in/check_out 추가 인식)
-- "Could not find the '...' column ... in the schema cache" 오류 즉시 해결
-- ※ NOTIFY가 즉시 반영되지 않는 경우: Supabase 대시보드 Settings → API → Reload schema 클릭
NOTIFY pgrst, 'reload schema';

-- 3) 기존 type/time 방식 데이터를 check_in/check_out 방식으로 마이그레이션
DO $$
BEGIN
  -- type 컬럼이 존재하는 경우에만 마이그레이션 수행
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'attendance' AND column_name = 'type'
  ) THEN
    -- NOT NULL 제약 제거 (새 행은 type 없이 삽입되므로 nullable로 변경)
    ALTER TABLE attendance ALTER COLUMN type DROP NOT NULL;

    -- 입실(in) 행의 time → check_in 마이그레이션
    UPDATE attendance
    SET check_in = time,
        method   = COALESCE(method, 'manual')
    WHERE type = 'in'
      AND time IS NOT NULL
      AND check_in IS NULL;

    -- 퇴실(out) 행의 time → 해당 학생+날짜의 check_out 마이그레이션
    UPDATE attendance a_in
    SET check_out = (
      SELECT a_out.time
      FROM attendance a_out
      WHERE a_out.student_id = a_in.student_id
        AND a_out.date       = a_in.date
        AND a_out.course_id  IS NOT DISTINCT FROM a_in.course_id
        AND a_out.type       = 'out'
      ORDER BY a_out.created_at DESC
      LIMIT 1
    )
    WHERE a_in.type = 'in';

    -- 퇴실(out) 전용 행 삭제 (check_out은 이미 in 행에 반영됨)
    DELETE FROM attendance WHERE type = 'out';

    -- 중복 in 행 제거: (student_id, date, course_id) 기준 가장 최근 1건만 유지
    DELETE FROM attendance a
    WHERE a.id NOT IN (
      SELECT DISTINCT ON (student_id, date, COALESCE(course_id::TEXT, 'null'))
             id
      FROM attendance
      ORDER BY student_id, date, COALESCE(course_id::TEXT, 'null'), created_at DESC
    );

    -- status 정규화: NULL → 'U'(미확인), 'O'/'L'/'A' 값은 그대로 유지
    UPDATE attendance SET status = 'U' WHERE status IS NULL OR status NOT IN ('O','L','A','U');
  END IF;
END $$;

-- 4) 이전 유니크 제약 제거 (있는 경우)
DO $$
BEGIN
  -- attendance_student_date_type_key: 매우 오래된 이름
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'attendance_student_date_type_key'
  ) THEN
    ALTER TABLE attendance DROP CONSTRAINT attendance_student_date_type_key;
  END IF;
  -- attendance_student_date_course_unique: 일부 환경에서 사용된 이전 이름
  -- 새 이름(attendance_student_date_course_key)으로 통일하기 위해 제거
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'attendance_student_date_course_unique'
  ) THEN
    ALTER TABLE attendance DROP CONSTRAINT attendance_student_date_course_unique;
  END IF;
  -- 동일 이름의 인덱스가 있을 경우에도 제거 (constraint가 아닌 index로 생성된 경우 대비)
  IF EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE tablename = 'attendance' AND indexname = 'attendance_student_date_course_unique'
  ) THEN
    DROP INDEX IF EXISTS attendance_student_date_course_unique;
  END IF;
END $$;

-- 4b) (student_id, date, course_id) 기준 중복 행 무조건 제거
--     type 컬럼 유무와 무관하게 실행 -- 새 유니크 제약 추가 전 데이터 정합성 보장
DELETE FROM attendance a
WHERE a.id NOT IN (
  SELECT DISTINCT ON (student_id, date, COALESCE(course_id::TEXT, 'null'))
         id
  FROM attendance
  ORDER BY student_id, date, COALESCE(course_id::TEXT, 'null'), created_at DESC
);

-- 5) 새 유니크 제약 추가: 학생+날짜+과정 기준 UPSERT 지원
--    course_id=NULL 허용 환경을 위해 NULLS NOT DISTINCT 사용 (PG15+)
--    PG14 이하 환경에서는 부분 인덱스로 대체
DO $$
DECLARE
  -- server_version_num 형식: 150001 = PG 15.0.1 → 10000으로 나누면 메이저 버전(15)
  pg_major INT := current_setting('server_version_num')::INT / 10000;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'attendance_student_date_course_key'
  ) AND NOT EXISTS (
    -- 인덱스로만 존재하는 경우도 체크 (CREATE UNIQUE INDEX로 생성된 경우 pg_constraint에 없음)
    SELECT 1 FROM pg_indexes
    WHERE tablename = 'attendance' AND indexname = 'attendance_student_date_course_key'
  ) THEN
    IF pg_major >= 15 THEN
      -- PostgreSQL 15+: NULLS NOT DISTINCT 지원
      EXECUTE 'ALTER TABLE attendance ADD CONSTRAINT attendance_student_date_course_key
               UNIQUE NULLS NOT DISTINCT (student_id, date, course_id)';
    ELSE
      -- PostgreSQL 14 이하: course_id NOT NULL 행만 커버하는 인덱스
      EXECUTE 'CREATE UNIQUE INDEX IF NOT EXISTS attendance_student_date_course_key
               ON attendance (student_id, date, course_id)
               WHERE course_id IS NOT NULL';
    END IF;
  END IF;
END $$;

-- 강사 테이블
CREATE TABLE IF NOT EXISTS instructors (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  type        TEXT DEFAULT '주강사',
  subject     TEXT DEFAULT '',
  phone       TEXT DEFAULT '',
  email       TEXT DEFAULT '',
  career      TEXT DEFAULT '',
  cert        TEXT DEFAULT '',
  cids        JSONB DEFAULT '[]'::JSONB,
  note        TEXT DEFAULT '',
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 강의실 테이블
CREATE TABLE IF NOT EXISTS rooms (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  addr        TEXT DEFAULT '',
  capacity    INTEGER DEFAULT 20,
  equip       TEXT DEFAULT '',
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 강의실 예약(배정) 테이블
CREATE TABLE IF NOT EXISTS room_bookings (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id     BIGINT REFERENCES rooms(id) ON DELETE CASCADE,
  course_id   BIGINT REFERENCES courses(id) ON DELETE CASCADE,
  label       TEXT DEFAULT '',
  start_date  TEXT NOT NULL,
  end_date    TEXT NOT NULL,
  color       TEXT DEFAULT '#EA580C',
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 계정 테이블
CREATE TABLE IF NOT EXISTS accounts (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  role        TEXT DEFAULT 'staff',
  pw          TEXT NOT NULL,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 2. 초기 관리자 계정 등록
-- ==========================================
INSERT INTO accounts (name, role, pw)
VALUES ('관리자', 'admin', 'admin1234')
ON CONFLICT DO NOTHING;

-- ==========================================
-- 3. 기본 강의실 데이터 등록
-- ==========================================
INSERT INTO rooms (name, addr, capacity, equip) VALUES
  ('101호 강의실', '의정부시 청사로 1',  25, '빔프로젝터·PC 25대·화이트보드'),
  ('세미나실 A',   '의정부시 청사로 1',  15, 'TV·노트북 연결'),
  ('컴퓨터실',     '양주시 남면로 20',   20, 'PC 20대·프린터')
ON CONFLICT DO NOTHING;

-- ==========================================
-- 4. RLS (Row Level Security) 해제
-- 관리자 내부 행정 시스템 — 인증은 앱 레벨에서 처리
-- ==========================================
ALTER TABLE courses       DISABLE ROW LEVEL SECURITY;
ALTER TABLE students      DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendance    DISABLE ROW LEVEL SECURITY;
ALTER TABLE instructors   DISABLE ROW LEVEL SECURITY;
ALTER TABLE rooms         DISABLE ROW LEVEL SECURITY;
ALTER TABLE room_bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE accounts      DISABLE ROW LEVEL SECURITY;

-- ==========================================
-- 5. Realtime 파이프라인 활성화
-- ==========================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
END
$$;

-- 전체 테이블 실시간 구독 대상으로 등록
ALTER PUBLICATION supabase_realtime
  ADD TABLE courses, students, attendance, instructors, rooms, room_bookings, accounts;

-- ==========================================
-- 6. PDF Storage 버킷 생성 및 공개 접근 허용
-- ==========================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('course-pdfs', 'course-pdfs', true)
ON CONFLICT (id) DO NOTHING;

-- Storage 정책: 업로드/다운로드 모두 허용
DROP POLICY IF EXISTS "public_course_pdfs" ON storage.objects;
CREATE POLICY "public_course_pdfs" ON storage.objects
  FOR ALL
  USING (bucket_id = 'course-pdfs')
  WITH CHECK (bucket_id = 'course-pdfs');

-- ==========================================
-- 7. 출결률 자동 계산 함수 & 트리거
-- 출결 INSERT/UPDATE/DELETE 시 student.rate 자동 갱신
-- ==========================================
CREATE OR REPLACE FUNCTION update_student_rate()
RETURNS TRIGGER AS $$
DECLARE
  v_student_id BIGINT;
  v_cid        BIGINT;
  v_date_from  TEXT;
  v_date_to    TEXT;
  total_days   INTEGER;
  attended_days INTEGER;
  new_rate     NUMERIC;
BEGIN
  -- 영향받는 student_id 결정
  IF TG_OP = 'DELETE' THEN
    v_student_id := OLD.student_id;
  ELSE
    v_student_id := NEW.student_id;
  END IF;

  -- 해당 학생의 과정 정보 가져오기
  SELECT cid INTO v_cid FROM students WHERE id = v_student_id;
  IF v_cid IS NULL THEN
    IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
  END IF;

  SELECT date_from, date_to INTO v_date_from, v_date_to
  FROM courses WHERE id = v_cid;

  -- 과정 전체 수업일 수 계산 (오늘까지만)
  SELECT COUNT(DISTINCT gs::date)
  INTO total_days
  FROM generate_series(
    v_date_from::date,
    LEAST(COALESCE(v_date_to::date, CURRENT_DATE), CURRENT_DATE),
    '1 day'::interval
  ) gs
  WHERE EXTRACT(DOW FROM gs::date) NOT IN (0, 6); -- 주말 제외

  IF total_days = 0 THEN RETURN NEW; END IF;

  -- 학생이 실제 출석한 날 수 (check_in 기록 또는 결석 외 status 기준)
  SELECT COUNT(DISTINCT date)
  INTO attended_days
  FROM attendance
  WHERE student_id = v_student_id
    -- 출석(O)·지각(L)만 출석일로 집계; 결석(A)·미확인(U)은 미출석 처리
    AND status IN ('O', 'L');

  new_rate := ROUND(LEAST((attended_days::NUMERIC / total_days) * 100, 100), 1);

  UPDATE students SET rate = new_rate WHERE id = v_student_id;

  IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
END;
$$ LANGUAGE plpgsql;

-- 기존 트리거 제거 후 재생성
DROP TRIGGER IF EXISTS trg_attendance_rate ON attendance;
CREATE TRIGGER trg_attendance_rate
  AFTER INSERT OR UPDATE OR DELETE ON attendance
  FOR EACH ROW EXECUTE FUNCTION update_student_rate();

-- ==========================================
-- 8. 컬럼 마이그레이션 (이미 실행한 DB도 안전하게 업데이트)
-- 이전 버전 SQL로 만든 DB에 누락된 컬럼을 추가합니다.
-- IF NOT EXISTS 덕분에 이미 있는 컬럼은 무시됩니다.
-- ==========================================
ALTER TABLE students ADD COLUMN IF NOT EXISTS addr_detail TEXT DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS addr_city   TEXT DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS phone2      TEXT DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS id_back     TEXT DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS itv_date    TEXT;
ALTER TABLE students ADD COLUMN IF NOT EXISTS itv_score   NUMERIC;
ALTER TABLE students ADD COLUMN IF NOT EXISTS itv_grade   TEXT DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS itv_pass    BOOLEAN DEFAULT FALSE;
ALTER TABLE students ADD COLUMN IF NOT EXISTS disabled    BOOLEAN DEFAULT FALSE;
ALTER TABLE students ADD COLUMN IF NOT EXISTS veteran     BOOLEAN DEFAULT FALSE;
ALTER TABLE students ADD COLUMN IF NOT EXISTS memo        TEXT DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS rate        NUMERIC DEFAULT 0;
-- 이전 버전 DB에 cid 컬럼이 없는 경우 추가
ALTER TABLE students ADD COLUMN IF NOT EXISTS cid         BIGINT REFERENCES courses(id) ON DELETE SET NULL;

ALTER TABLE courses  ADD COLUMN IF NOT EXISTS pdf_name   TEXT;
ALTER TABLE courses  ADD COLUMN IF NOT EXISTS pdf_data   TEXT;
ALTER TABLE courses  ADD COLUMN IF NOT EXISTS links      JSONB DEFAULT '[]'::JSONB;
ALTER TABLE courses  ADD COLUMN IF NOT EXISTS sched_days      TEXT;
ALTER TABLE courses  ADD COLUMN IF NOT EXISTS sched_time_from TEXT;
ALTER TABLE courses  ADD COLUMN IF NOT EXISTS sched_time_to   TEXT;
ALTER TABLE courses  ADD COLUMN IF NOT EXISTS notes      TEXT;
ALTER TABLE courses  ADD COLUMN IF NOT EXISTS c_goal     INTEGER DEFAULT 0;
ALTER TABLE courses  ADD COLUMN IF NOT EXISTS e_goal     INTEGER DEFAULT 0;

ALTER TABLE instructors ADD COLUMN IF NOT EXISTS cids JSONB DEFAULT '[]'::JSONB;
ALTER TABLE instructors ADD COLUMN IF NOT EXISTS note TEXT DEFAULT '';

-- ==========================================
-- 9. PostgREST 스키마 캐시 강제 갱신
-- 새 컬럼 추가 후 PostgREST가 즉시 인식하도록 알림을 전송합니다.
-- "Could not find the '...' column ... in the schema cache" 오류 해결
-- ※ NOTIFY가 즉시 반영되지 않는 경우:
--   Supabase 대시보드 → 설정(Settings) → API → "Reload schema" 버튼 클릭
-- ==========================================
NOTIFY pgrst, 'reload schema';

-- ==========================================
-- 10. 출결 사유 컬럼 추가 (별지 83호 수강증명서 지원)
-- reason: 결석 사유 메모 (자유 입력)
-- absence_type: 결석 유형 ('excused'=부득이한사유, 'personal'=개인사유)
-- ==========================================
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS reason       TEXT;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS absence_type TEXT;

-- HRD 출결 기준 변경: 지각(L) 폐지 → 기존 지각 기록을 출석(O)으로 일괄 전환
-- (일일 총 훈련시간의 50% 이상 참여 시 '출석', 미만 시 '결석'으로 새로 운영)
UPDATE attendance SET status = 'O' WHERE status = 'L';

-- 상태 주석 업데이트: O=출석, A=결석, U=미확인 (L=지각 폐지)
COMMENT ON COLUMN attendance.status IS 'O=출석, A=결석, U=미확인 (지각 폐지: HRD 기준 변경)';

NOTIFY pgrst, 'reload schema';

-- ==========================================
-- ✅ 완료! 이제 index.html을 새로고침하세요
-- ==========================================
