-- ============================================================
-- 경기북부 직업교육 학사관리시스템 — Supabase 초기 세팅 스크립트
-- Supabase SQL Editor에서 전체 복사 → Run (Ctrl+Enter)
-- ============================================================

-- ==========================================
-- 1. 데이터베이스 테이블 생성
-- ==========================================

-- 과정 테이블
CREATE TABLE IF NOT EXISTS courses (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cat         TEXT,
  cc          TEXT,
  name        TEXT NOT NULL,
  code        TEXT,
  date_from   TEXT,
  date_to     TEXT,
  period      TEXT,
  method      TEXT,
  hours       NUMERIC,
  tgt         INTEGER DEFAULT 0,
  c_goal      INTEGER DEFAULT 0,
  e_goal      INTEGER DEFAULT 0,
  sched_days  TEXT,
  sched_time_from TEXT,
  sched_time_to   TEXT,
  notes       TEXT,
  pdf_name    TEXT,
  pdf_data    TEXT,
  links       JSONB DEFAULT '[]'::JSONB,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 훈련생 테이블 (id는 IDENTITY — 앱이 직접 생성하지 않음)
CREATE TABLE IF NOT EXISTS students (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cid         BIGINT REFERENCES courses(id) ON DELETE SET NULL,
  name        TEXT NOT NULL,
  gender      TEXT DEFAULT '',
  birth       TEXT,
  id_back     TEXT DEFAULT '',
  phone       TEXT DEFAULT '',
  phone2      TEXT DEFAULT '',
  addr_city   TEXT DEFAULT '',
  addr_detail TEXT DEFAULT '',
  edu         TEXT DEFAULT '',
  major       TEXT DEFAULT '',
  career      TEXT DEFAULT '',
  cert        TEXT DEFAULT '',
  status      TEXT DEFAULT '미취업',
  unemp       BOOLEAN DEFAULT FALSE,
  disabled    BOOLEAN DEFAULT FALSE,
  veteran     BOOLEAN DEFAULT FALSE,
  itv_date    TEXT,
  itv_score   NUMERIC,
  itv_grade   TEXT DEFAULT '',
  itv_pass    BOOLEAN DEFAULT FALSE,
  memo        TEXT DEFAULT '',
  rate        NUMERIC DEFAULT 0,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 출결 테이블
CREATE TABLE IF NOT EXISTS attendance (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id  BIGINT REFERENCES students(id) ON DELETE CASCADE,
  date        TEXT NOT NULL,
  type        TEXT NOT NULL CHECK (type IN ('in','out')),
  time        TEXT,
  status      TEXT DEFAULT 'O',
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 강사 테이블
CREATE TABLE IF NOT EXISTS instructors (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  type        TEXT DEFAULT '주강사',
  subject     TEXT DEFAULT '',
  phone       TEXT DEFAULT '',
  email       TEXT DEFAULT '',
  career      TEXT DEFAULT '',
  cert        TEXT DEFAULT '',
  cids        JSONB DEFAULT '[]'::JSONB,
  note        TEXT DEFAULT '',
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 강의실 테이블
CREATE TABLE IF NOT EXISTS rooms (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  addr        TEXT DEFAULT '',
  capacity    INTEGER DEFAULT 20,
  equip       TEXT DEFAULT '',
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 강의실 예약(배정) 테이블
CREATE TABLE IF NOT EXISTS room_bookings (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id     BIGINT REFERENCES rooms(id) ON DELETE CASCADE,
  course_id   BIGINT REFERENCES courses(id) ON DELETE CASCADE,
  label       TEXT DEFAULT '',
  start_date  TEXT NOT NULL,
  end_date    TEXT NOT NULL,
  color       TEXT DEFAULT '#EA580C',
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 계정 테이블
CREATE TABLE IF NOT EXISTS accounts (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  role        TEXT DEFAULT 'staff',
  pw          TEXT NOT NULL,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 2. 초기 관리자 계정 등록
-- ==========================================
INSERT INTO accounts (name, role, pw)
VALUES ('관리자', 'admin', 'admin1234')
ON CONFLICT DO NOTHING;

-- ==========================================
-- 3. 기본 강의실 데이터 등록
-- ==========================================
INSERT INTO rooms (name, addr, capacity, equip) VALUES
  ('101호 강의실', '의정부시 청사로 1',  25, '빔프로젝터·PC 25대·화이트보드'),
  ('세미나실 A',   '의정부시 청사로 1',  15, 'TV·노트북 연결'),
  ('컴퓨터실',     '양주시 남면로 20',   20, 'PC 20대·프린터')
ON CONFLICT DO NOTHING;

-- ==========================================
-- 4. RLS (Row Level Security) 해제
-- 관리자 내부 행정 시스템 — 인증은 앱 레벨에서 처리
-- ==========================================
ALTER TABLE courses       DISABLE ROW LEVEL SECURITY;
ALTER TABLE students      DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendance    DISABLE ROW LEVEL SECURITY;
ALTER TABLE instructors   DISABLE ROW LEVEL SECURITY;
ALTER TABLE rooms         DISABLE ROW LEVEL SECURITY;
ALTER TABLE room_bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE accounts      DISABLE ROW LEVEL SECURITY;

-- ==========================================
-- 5. Realtime 파이프라인 활성화
-- ==========================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
END
$$;

-- 핵심 테이블만 실시간 구독 대상으로 등록
ALTER PUBLICATION supabase_realtime
  ADD TABLE courses, students, attendance;

-- ==========================================
-- 6. PDF Storage 버킷 생성 및 공개 접근 허용
-- ==========================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('course-pdfs', 'course-pdfs', true)
ON CONFLICT (id) DO NOTHING;

-- Storage 정책: 업로드/다운로드 모두 허용
DROP POLICY IF EXISTS "public_course_pdfs" ON storage.objects;
CREATE POLICY "public_course_pdfs" ON storage.objects
  FOR ALL
  USING (bucket_id = 'course-pdfs')
  WITH CHECK (bucket_id = 'course-pdfs');

-- ==========================================
-- 7. 출결률 자동 계산 함수 & 트리거
-- 출결 INSERT/UPDATE/DELETE 시 student.rate 자동 갱신
-- ==========================================
CREATE OR REPLACE FUNCTION update_student_rate()
RETURNS TRIGGER AS $$
DECLARE
  v_student_id BIGINT;
  v_cid        BIGINT;
  v_date_from  TEXT;
  v_date_to    TEXT;
  total_days   INTEGER;
  attended_days INTEGER;
  new_rate     NUMERIC;
BEGIN
  -- 영향받는 student_id 결정
  IF TG_OP = 'DELETE' THEN
    v_student_id := OLD.student_id;
  ELSE
    v_student_id := NEW.student_id;
  END IF;

  -- 해당 학생의 과정 정보 가져오기
  SELECT cid INTO v_cid FROM students WHERE id = v_student_id;
  IF v_cid IS NULL THEN
    IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
  END IF;

  SELECT date_from, date_to INTO v_date_from, v_date_to
  FROM courses WHERE id = v_cid;

  -- 과정 전체 수업일 수 계산 (오늘까지만)
  SELECT COUNT(DISTINCT gs::date)
  INTO total_days
  FROM generate_series(
    v_date_from::date,
    LEAST(COALESCE(v_date_to::date, CURRENT_DATE), CURRENT_DATE),
    '1 day'::interval
  ) gs
  WHERE EXTRACT(DOW FROM gs::date) NOT IN (0, 6); -- 주말 제외

  IF total_days = 0 THEN RETURN NEW; END IF;

  -- 학생이 실제 출석한 날 수 (입실(type='in') 기준)
  SELECT COUNT(DISTINCT date)
  INTO attended_days
  FROM attendance
  WHERE student_id = v_student_id AND type = 'in';

  new_rate := ROUND(LEAST((attended_days::NUMERIC / total_days) * 100, 100), 1);

  UPDATE students SET rate = new_rate WHERE id = v_student_id;

  IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
END;
$$ LANGUAGE plpgsql;

-- 기존 트리거 제거 후 재생성
DROP TRIGGER IF EXISTS trg_attendance_rate ON attendance;
CREATE TRIGGER trg_attendance_rate
  AFTER INSERT OR UPDATE OR DELETE ON attendance
  FOR EACH ROW EXECUTE FUNCTION update_student_rate();

-- ==========================================
-- ✅ 완료! 이제 index.html을 새로고침하세요
-- ==========================================
